from __future__ import annotations

import argparse
import logging
import re
import sys
from pathlib import Path

# precompile regex patterns
CN_API_LABEL_PATTERN = re.compile(r".. _([a-zA-Z0-9_]+):")
REF_PATTERN = re.compile(r":ref:`([^`]+)`")
API_LABEL_EXTRACT_PATTERN = re.compile(r".+?<(?P<api_label>.+?)>")
CN_API_PREFIX = "cn_api_paddle"

logger = logging.getLogger()
if logger.handlers:
    # we assume the first handler is the one we want to configure
    console = logger.handlers[0]
else:
    console = logging.StreamHandler()
    logger.addHandler(console)
console.setFormatter(
    logging.Formatter(
        "%(asctime)s - %(funcName)s:%(lineno)d - %(levelname)s - %(message)s"
    )
)
logger.setLevel(logging.INFO)


def check_api_label(file_path: Path, doc_root: Path) -> str | None:
    """Check if the first line of the file matches the expected api_label format."""
    with open(file_path, "r", encoding="utf-8") as f:
        first_line = f.readline().strip()
    except_line = generate_cn_label(file_path, doc_root)
    if first_line == except_line:
        return None
    return f"`{file_path}` first line is: `{first_line}`, but expected generated by path: `{except_line}`."


def generate_cn_label(file_path: Path, doc_root: Path) -> str:
    """Generate the expected api_label format from file path."""
    relative_path = file_path.relative_to(doc_root)
    stem = relative_path.stem.removesuffix("_cn")
    parts = relative_path.with_name(stem).parts
    label = "_".join(parts)
    return f".. _cn_{label}:"


def collect_api_labels(api_root: Path) -> set[str]:
    """Collect all valid api labels."""
    labels = set()
    for rst_file in api_root.rglob("*.rst"):
        if not rst_file.is_file():
            continue
        if not need_check(rst_file, api_root):
            continue
        labels.update(extract_api_labels(rst_file))
    return labels


def extract_api_labels(file_path: Path) -> set[str]:
    labels = set()
    with open(file_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
        for line in lines:
            match = CN_API_LABEL_PATTERN.search(line)
            if not match:
                continue
            label = match.group(1)
            if not label.startswith("cn_api_paddle"):
                continue
            labels.add(label)
    return labels


# api doc for checking
def need_check(file_path: Path, api_root: Path) -> bool:
    return (
        file_path.name.endswith("_cn.rst")
        and file_path.name not in {"Overview_cn.rst", "index_cn.rst"}
        and file_path.is_relative_to(api_root)
    )


def validate_api_label_references(
    files: list[Path], valid_api_labels: set[str]
) -> list[str]:
    errors = []
    for file in files:
        with open(file, "r", encoding="utf-8") as f:
            content = f.read()
        matches = REF_PATTERN.findall(content)
        for match in matches:
            api_label = match
            if api_label_match := API_LABEL_EXTRACT_PATTERN.match(api_label):
                api_label = api_label_match.group("api_label")
            if not api_label.startswith(CN_API_PREFIX):
                continue
            if api_label in valid_api_labels:
                continue
            errors.append(f"api label `{api_label}` in `{file}`")
    return errors


def get_custom_files_for_checking_usage(api_root: Path) -> set[Path]:
    # TODO: add more dir for checking
    custom_files = set()
    for rst_file in api_root.rglob("*.rst"):
        if not rst_file.is_file():
            continue
        if rst_file.name in {"set_global_initializer_cn.rst"}:
            # TODO: how to deal with `api_paddle_Tensor_create_tensor`?
            continue
        custom_files.add(rst_file)
    return custom_files


def run_cn_api_label_checking(
    doc_root: Path, api_root: Path, files: list[Path]
) -> None:
    # get real path for changed files
    real_path_files_set = set(files)

    errors = []
    # check the api_label in the first line for increased files
    for file_path in real_path_files_set:
        if not need_check(file_path, api_root):
            continue
        if error := check_api_label(file_path, doc_root):
            errors.append(error)
    if errors:
        logger.error(
            "Found first line is not available as follows, please re-check it!"
        )
        for i, error in enumerate(errors, 1):
            logger.error(f"{i}: {error}")
        sys.exit(1)

    # collect all api_labels in api_root
    valid_api_labels = collect_api_labels(api_root)

    # check the usage of api_label in custom files
    need_uasge_check_files = set()
    for file_path in real_path_files_set:
        if not file_path.is_relative_to(doc_root):
            continue
        if file_path.suffix != ".rst":
            continue
        need_uasge_check_files.add(file_path)

    api_label_usage_file_set = (
        need_uasge_check_files | get_custom_files_for_checking_usage(doc_root)
    )

    if errors := validate_api_label_references(
        api_label_usage_file_set, valid_api_labels
    ):
        logger.error(
            "Found valid api labels usage as follows, please re-check it!"
        )
        for i, error in enumerate(errors, 1):
            logger.error(f"{i}: {error}")
        sys.exit(1)

    print("All api_label check success in PR !")


def parse_args():
    """
    Parse input arguments
    """
    parser = argparse.ArgumentParser(description="cn api_label checking")
    parser.add_argument(
        "doc_root",
        type=Path,
        help="the dir DOCROOT",
        default=Path("/FluidDoc/docs"),
    )

    parser.add_argument(
        "api_root",
        type=Path,
        help="the dir api_root",
        default=Path("/FluidDoc/docs/api"),
    )
    parser.add_argument(
        "all_git_files",
        type=Path,
        nargs="*",
        help="files need to check",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    run_cn_api_label_checking(args.doc_root, args.api_root, args.all_git_files)
