[files]
# The following files will be excluded from spell check during commits
extend-exclude = [
     # Skip `Accuray ` check in these files
    "docs/practices/cv/3D_image_classification_from_CT_scans.ipynb",

]

[default]
# Ignore 1-3 letter words, refer to https://github.com/crate-ci/typos/issues/1079
extend-ignore-words-re = ["^[a-zA-Z]{1,3}$"]
# refer to https://github.com/crate-ci/typos/blob/master/docs/reference.md#example-configurations
extend-ignore-re = [
    # Ignore lines by `# typos: disable-line`
    "(?Rm)^.*(#|//)\\s*typos:\\s*disable-line$",
    # Ignore block by `# typos: off` and `# typos: on`
    "(?s)(#|//)\\s*typos:\\s*off.*?\\n\\s*(#|//)\\s*typos:\\s*on"
]

[default.extend-words]
# PaddlePaddle specific words
CANN = "CANN"
Clas = "Clas"
arange = "arange"
unsupport = "unsupport"
Nervana = "Nervana"
datas = "datas"
feeded = "feeded"

# These words need to be fixed
Learing = "Learing"
Operaton = "Operaton"
Optimizaing = "Optimizaing"
Optimzier = "Optimzier"
Setment = "Setment"
Simle = "Simle"
Sovler = "Sovler"
inferface = "inferface"
infor = "infor"
instert = "instert"
instrinsics = "instrinsics"
interchangable = "interchangable"
intializers = "intializers"
intput = "intput"
libary = "libary"
matrics = "matrics"
metrices = "metrices"
mutbale = "mutbale"
occurence = "occurence"
opeartor = "opeartor"
opeartors = "opeartors"
operaters = "operaters"
optmization = "optmization"
outpu = "outpu"
outpus = "outpus"
overrided = "overrided"
overwrited = "overwrited"
samle = "samle"
schedual = "schedual"
secenarios = "secenarios"
sematic = "sematic"
seperator = "seperator"
setted = "setted"
shoule = "shoule"
similary = "similary"
simplier = "simplier"
skiped = "skiped"
softwares = "softwares"
specail = "specail"
sperated = "sperated"
splited = "splited"
splitted = "splitted"
stirng = "stirng"
stradegy = "stradegy"
subract = "subract"
sucess = "sucess"
sucessor = "sucessor"
sucessors = "sucessors"
szie = "szie"
