[tool.black]
exclude = "build"
line-length = 80
skip-string-normalization = true

[tool.ruff]
target-version = "py37"
select = [
    # Pycodestyle
    "E",
    "W",

    # Pyflakes
    "F",

    # Isort
    "I",

    # Comprehensions
    "C4",

    # Pyupgrade
    "UP",

    # NumPy-specific rules
    "NPY001",
    "NPY003",

    # Bugbear
    "B002",
    "B003",
    "B004",
    "B009",
    "B010",
    "B011",
    "B012",
    "B013",
    "B014",
    "B015",
    "B016",
    "B017",
    "B018",
    "B019",
    "B020",
    "B021",
    "B022",
    "B025",
    "B029",
    "B032",

    # Pylint
    "PLE",
    "PLC0414",
    "PLC3002",
    "PLR0206",
    "PLR0402",
    "PLR1701",
    "PLR1711",
    "PLR1722",
    "PLW3301",

    # Pygrep-hooks
    "PGH004",
]
unfixable = [
    "NPY001"
]
ignore = [
    "E402",
    "E501",
    "E722",
    "E731",
    "E741",
    "F841",
    "UP015",
    "UP038",
    # need to remove
    "F541",
    "I001",
    "UP032",
    "F401",
    "UP025",
    "W291",
    "PLR1722",
    "C403",
    "C405",
    "C414",
    "C416",
    "C419",
    "E401",
    "E711",
    "E712",
    "F811",
    "F821"
]
