name:  📝 分布式文档——参数服务器(Parameter Sever)快速开始体验评估 Eval Issue
description: 第六期分布式文档——参数服务器(Parameter Sever)快速开始体验评估报告。
labels: [distributed_ps_eval]

body:
- type: markdown
  attributes:
    value: >
      #### 此模板用于第六期分布式文档-参数服务器(Parameter Sever)快速开始评估工作小组成员，向飞桨团队反馈文档问题。如非工作小组成员，请使用 「📚文档」模板，感谢配合~

      #### This template is used by members of the distributed document evaluation working group to report documentation issues to the Paddle Team. If you are not a member of the working group, please use the "📚 Documentation Issue" template, thank you for your cooperation~

- type: dropdown
  id: distributed_ps_environment
  attributes:
    label: 项目环境
    description: 请选择您的项目运行环境
    options:
      - 云平台
      - 自己的硬件（如集群）
      - AI Studio
      - 其他
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      # 参数服务器(Parameter Sever)任务一 体验评估报告


- type: textarea
  id: distributed_ps_task1
  attributes:
    label: 认领任务
    description: |
      请输入您认领的任务名称，并附上链接（如果有）。
      例：CTR-DNN
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      ## 任务一体验评测
      
- type: textarea
  id: distributed_ps_eval1
  attributes:
    label: 1.导入分布式训练需要的依赖包
    description: |
      针对 导入分布式训练需要的依赖	这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true

- type: textarea
  id: distributed_ps_eval2
  attributes:
    label: 2.定义分布式模式并初始化分布式训练环境
    description: |
      针对 定义分布式模式并初始化分布式训练环境	这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true

- type: textarea
  id: distributed_ps_eval3
  attributes:
    label: 3.加载模型
    description: |
      针对 加载模型	这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true


- type: textarea
  id: distributed_ps_eval4
  attributes:
    label: 4.构建 dataset 加载数据
    description: |
      针对 构建 dataset 加载数据 这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true
    
- type: textarea
  id: distributed_ps_eval5
  attributes:
    label: 5.定义参数更新策略及优化器
    description: |
      针对 定义参数更新策略及优化器 这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true
    
- type: textarea
  id: distributed_ps_eval6
  attributes:
    label: 6.开始多机分布式训练
    description: |
      针对 开始多机分布式训练 这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true
    
- type: textarea
  id: distributed_ps_eval7
  attributes:
    label: 其他问题或建议
    description: |
     如果有其他问题或建议，请您详细描述。
  validations:
    required: false

- type: textarea
  id: distributed_ps_code1
  attributes:
    label: 相关代码
    description: |
      请附上aistudio项目地址 或 直接贴示例代码
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      # 参数服务器(Parameter Sever)任务二 体验评估报告


- type: textarea
  id: distributed_ps_task2
  attributes:
    label: 认领任务名称
    description: |
      请输入您认领的任务名称，并附上链接（如果有）。
      例：DSSM文本匹配模型
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      ## 任务二体验评测
      
- type: textarea
  id: distributed_ps_eval11
  attributes:
    label: 1.导入分布式训练需要的依赖包
    description: |
      针对 导入分布式训练需要的依赖	这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true

- type: textarea
  id: distributed_ps_eval12
  attributes:
    label: 2.定义分布式模式并初始化分布式训练环境
    description: |
      针对 定义分布式模式并初始化分布式训练环境	这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true

- type: textarea
  id: distributed_ps_eval13
  attributes:
    label: 3.加载模型
    description: |
      针对 加载模型	这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true


- type: textarea
  id: distributed_ps_eval14
  attributes:
    label: 4.构建 dataset 加载数据
    description: |
      针对 构建 dataset 加载数据 这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true
    
- type: textarea
  id: distributed_ps_eval15
  attributes:
    label: 5.定义参数更新策略及优化器
    description: |
      针对 定义参数更新策略及优化器 这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true
    
- type: textarea
  id: distributed_ps_eval16
  attributes:
    label: 6.开始多机分布式训练
    description: |
      针对 开始多机分布式训练 这一环节，请回答以下内容
    value: |
      - 完成情况（成功/不成功) ：
      - 遇到问题：
      - 解决方法（无法解决需注明)：
      - 对应文档是否描述清晰（如不清晰，需注明问题并提供文档链接）：
  validations:
    required: true

- type: textarea
  id: distributed_ps_eval17
  attributes:
    label: 其他问题或建议
    description: |
     如果有其他问题或建议，请您详细描述。
  validations:
    required: false

- type: textarea
  id: distributed_ps_code2
  attributes:
    label: 相关代码
    description: |
      请附上aistudio项目地址 或 直接贴示例代码
  validations:
    required: true


- type: markdown
  attributes:
    value: >
      感谢你的贡献 🎉！Thanks for your contribution 🎉!
      
