from easydict import EasyDict as edict
import numpy as np

__C = edict()
cfg = __C

__C.TRAIN = edict()

__C.IMG_WIDTH = 300
__C.IMG_HEIGHT = 300
__C.IMG_CHANNEL = 3
__C.CLASS_NUM = 21
__C.BACKGROUND_ID = 0

# training settings
__C.TRAIN.MOMENTUM = 0.9
__C.TRAIN.BATCH_SIZE = 32
__C.TRAIN.LEARNING_RATE = 0.0005 / 4
#__C.TRAIN.LEARNING_RATE = 0.001 / __C.TRAIN.BATCH_SIZE
__C.TRAIN.NUM_PASS = 50000
__C.TRAIN.L2REGULARIZATION = 0.0005 * 4
#__C.TRAIN.L2REGULARIZATION = 0.0005 * __C.TRAIN.BATCH_SIZE
__C.TRAIN.LEARNING_RATE_DECAY_A = 0.1
__C.TRAIN.LEARNING_RATE_DECAY_B = 16551 * 80
__C.TRAIN.LEARNING_RATE_SCHEDULE = 'discexp'
#__C.TRAIN.LEARNING_RATE_SCHEDULE = 'constant'

__C.NET = edict()

# configuration for multibox_loss_layer
__C.NET.MBLOSS = edict()
__C.NET.MBLOSS.OVERLAP_THRESHOLD = 0.5
__C.NET.MBLOSS.NEG_POS_RATIO = 3.0
__C.NET.MBLOSS.NEG_OVERLAP = 0.5

# configuration for detection_map
__C.NET.DETMAP = edict()
__C.NET.DETMAP.OVERLAP_THRESHOLD = 0.5
__C.NET.DETMAP.EVAL_DIFFICULT = False
__C.NET.DETMAP.AP_TYPE = "11point"

# configuration for detection_output_layer
__C.NET.DETOUT = edict()
__C.NET.DETOUT.CONFIDENCE_THRESHOLD = 0.01
__C.NET.DETOUT.NMS_THRESHOLD = 0.45
__C.NET.DETOUT.NMS_TOP_K = 400
__C.NET.DETOUT.KEEP_TOP_K = 200

################################################
__C.NET.CONV11 = edict()
__C.NET.CONV11.PB = edict()
__C.NET.CONV11.PB.MIN_SIZE = [60]
__C.NET.CONV11.PB.ASPECT_RATIO = [2.]
#__C.NET.CONV11.PB.ASPECT_RATIO = [2.]
__C.NET.CONV11.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

__C.NET.CONV13 = edict()
__C.NET.CONV13.PB = edict()
__C.NET.CONV13.PB.MIN_SIZE = [105]
__C.NET.CONV13.PB.MAX_SIZE = [150]
__C.NET.CONV13.PB.ASPECT_RATIO = [2., 3.]
__C.NET.CONV13.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

__C.NET.CONV14_2 = edict()
__C.NET.CONV14_2.PB = edict()
__C.NET.CONV14_2.PB.MIN_SIZE = [150]
__C.NET.CONV14_2.PB.MAX_SIZE = [195]
__C.NET.CONV14_2.PB.ASPECT_RATIO = [2., 3.]
__C.NET.CONV14_2.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

__C.NET.CONV15_2 = edict()
__C.NET.CONV15_2.PB = edict()
__C.NET.CONV15_2.PB.MIN_SIZE = [195]
__C.NET.CONV15_2.PB.MAX_SIZE = [240]
__C.NET.CONV15_2.PB.ASPECT_RATIO = [2., 3.]
__C.NET.CONV15_2.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

__C.NET.CONV16_2 = edict()
__C.NET.CONV16_2.PB = edict()
__C.NET.CONV16_2.PB.MIN_SIZE = [240]
__C.NET.CONV16_2.PB.MAX_SIZE = [285]
__C.NET.CONV16_2.PB.ASPECT_RATIO = [2., 3.]
__C.NET.CONV16_2.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

__C.NET.CONV17_2 = edict()
__C.NET.CONV17_2.PB = edict()
__C.NET.CONV17_2.PB.MIN_SIZE = [285]
__C.NET.CONV17_2.PB.MAX_SIZE = [300]
__C.NET.CONV17_2.PB.ASPECT_RATIO = [2., 3.]
__C.NET.CONV17_2.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]
